apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata: 
  name: simplehttpapp
spec: 
  barURL: ""
  designerFlowsOperationMode: disabled
  license: 
    accept: true
    license: L-KSBM-C87FU2
    use: CloudPakForIntegrationNonProduction
  pod: 
    containers: 
      runtime: 
        image: "image-registry.openshift-image-registry.svc:5000/cp4i-202131/simplehttpapp:latest-amd64"
  replicas: 1
  service: 
    endpointType: http
  useCommonServices: true
  version: 12.0.2.0-r2
  configurations:
    - corsenabled2