apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata: 
  name: simplehttpapp
spec: 
  barURL: "https://cp4idevop.jfrog.io/artifactory/cp4iartefact/simplehttpapp.bar"
  designerFlowsOperationMode: disabled
  license: 
    accept: true
    license: L-KSBM-C87FU2
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  service: 
    endpointType: http
  useCommonServices: true
  adminServerSecure: true
  createDashboardUsers: true
  version: 12.0.2.0-r2
  configurations:
    - corsenabled2
    - jfrogauth