apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: simplehttpapp
  namespace: cp4i
spec:
  path: /test
  to:
    kind: Service
    name: oneclick-simplehttpapp-is
  port:
    targetPort: 7800